/*
 * OBO.h
 *
 *  Created on: 31 Oct 2012
 *      Author: alan
 */

#ifndef OBO_H_
#define OBO_H_

#include <string>
#include <vector>

#include <map>

#include <boost/shared_ptr.hpp>
//#include <boost/unordered_map.hpp>

#include "OBOTerm.h"

namespace ImzML {

	class OBO {
	private:
		std::string formatVersion;
		std::string data;
		std::string savedBy;
		std::string autogeneratedBy;
		std::string defaultNamespace;

		// Taken from the id, before the ':' e.g. IMS, MS, UO, PATO for faster matching of terms
		std::string ns;

		std::vector< boost::shared_ptr<OBO> > imports;
		std::vector<std::string> remarks;

		std::map<int , boost::shared_ptr<ImzML::OBOTerm> > terms;

	public:
		OBO();
		OBO(std::string filename);
		virtual ~OBO();

		void parse(std::string filename);

		boost::shared_ptr<ImzML::OBOTerm> getTerm(std::string id);
		boost::shared_ptr<ImzML::OBOTerm> getTerm(std::string ns, int id);

//		float load_factor() { return terms.load_factor(); }

	private:
		void cleanup();
	};

} /* namespace ImzML */
#endif /* OBO_H_ */
